#!/usr/bin/env python3
"""Turn probe results into a feed-health report (for the weekly GitHub Action).

Usage:
  python3 tools/feed_report.py [path/to/channels.json]

Reads the probe files (tools/feeds_probed.json, tools/grtv_probed.json) that
fetch_feeds.py produced and prints a Markdown report: channels with no
verified streams (pruning candidates), channels whose primary stream failed,
and confirmed-dead stream URLs. 'blocked'/'error' are flagged as
geo-ambiguous — the report notes they may be fine for viewers in Greece.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROBE_FILES = [os.path.join(HERE, "feeds_probed.json"), os.path.join(HERE, "grtv_probed.json")]


def load_json(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []


def main():
    feed_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "feed", "channels.json")
    data = load_json(feed_path)
    channels = data.get("channels") if isinstance(data, dict) else data
    if not isinstance(channels, list):
        raise SystemExit("No channel list found in %s" % feed_path)
    status_by_url = {}
    for pf in PROBE_FILES:
        for e in load_json(pf):
            url = e.get("url", "")
            if url:
                st = e.get("status") or ("ok" if e.get("ok") else "error")
                status_by_url[url] = st

    no_verified = []     # (name, statuses) — pruning candidates
    primary_down = []    # (name, statuses)
    dead_streams = []    # (name, url)
    alt_added_note = []

    for ch in channels:
        streams = ch.get("streams") or []
        if not streams:
            continue
        sts = []
        for s in streams:
            st = status_by_url.get(s.get("url", ""), "unprobed")
            sts.append(st)
            if st == "dead":
                dead_streams.append((ch.get("name"), s.get("url")))
        probed = [st for st in sts if st != "unprobed"]
        if not probed:
            continue  # not covered by this probe run (e.g. curated radio) — neutral
        ok_count = sum(1 for st in probed if st == "ok")
        if ok_count == 0:
            no_verified.append((ch.get("name"), sts))
        elif sts[0] != "unprobed" and sts[0] != "ok":
            primary_down.append((ch.get("name"), sts))

    out = []
    out.append("# Greek Express TV — Feed health report")
    out.append("")
    total = len(channels)
    with_ok = total - len(no_verified)
    out.append("- Channels: **%d** | with a verified stream: **%d** | needing attention: **%d**" % (
        total, with_ok, len(no_verified)))
    out.append("")
    out.append("Statuses: `ok` = HLS served · `dead` = HTTP 404/410 (gone) · "
               "`blocked` = 403 (often geo/hotlink) · `error` = unreachable · `unprobed` = not in this run")
    out.append("")

    if no_verified:
        out.append("## ⚠️ No verified stream (pruning candidates)")
        out.append("")
        out.append("| Channel | Stream statuses |")
        out.append("|---|---|")
        for name, sts in sorted(no_verified):
            out.append("| %s | %s |" % (name, ", ".join(sts)))
        out.append("")
        out.append("> These have no stream this runner could verify. `blocked`/`error` may be "
                   "runner-geo only — check from a Greek IP before removing.")
        out.append("")
    else:
        out.append("## ✅ No channels lost all verified streams")
        out.append("")

    if primary_down:
        out.append("## Primary down, alternates OK")
        out.append("")
        out.append("| Channel | Stream statuses |")
        out.append("|---|---|")
        for name, sts in sorted(primary_down):
            out.append("| %s | %s |" % (name, ", ".join(sts)))
        out.append("")

    if dead_streams:
        out.append("## ☠️ Confirmed dead streams (HTTP 404/410)")
        out.append("")
        for name, url in sorted(set(dead_streams)):
            out.append("- %s — `%s`" % (name, url))
        out.append("")

    out.append("_Generated by the weekly feed-health workflow._")
    print("\n".join(out))


if __name__ == "__main__":
    main()
